### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by SamsadSajid** [azmainadel/bmi-flutter#1]
in the `lib/utils/constants.dart` file `kLabelTextStyle, kGeneralTextStyle` these types of name kinda does't tell anything about the variable.

**Comment by SamsadSajid** [comment]
:P

**Comment by azmainadel** [comment]
My life, my rules. :zap: :zap: :zap:
Jokes apart, I'll keep that in mind.

Where can I reach you without thinking about "will he reply within two days?"?
**Slack/Messenger/Mail**?

**Comment by SamsadSajid** [comment]
I was implementing the demo I told you about last night. With `flutter_bloc` and `dio`, to implement the UI with event based architecture. The thing is after writing the codes, when I looked at it, it felt like if you don't go through this => [bloc pattern architecture](https://bloclibrary.dev/#/flutterbloccoreconcepts) it's not gonna be helpful for you.
